accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
        # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
    
    path('mypage/',
         views.MyPageView.as_view(),
         name = 'mypage')
    ]

bookshop_app/urls.py
from django.urls import path
from . import views 


app_name = 'bookshop'

urlpatterns = [
path('',views.IndexView.as_view(), name = 'index'),
path ('photo-detail/<int:pk>/',
      views.BookDetailView.as_view(),
      name='book_detail'),
path('cart/', views.cart_detail, name='cart_detail'),
path('cart/add/<int:book_id>/', views.add_to_cart, 
     name='add_to_cart'),
path('cart/remove/<int:item_id>/', views.remove_cart_item,
     name='remove_cart_item'),
path ('contact/', views.ContactView.as_view(),
      name = 'contact')
]

bookshopproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookshop/',include('bookshop_app.urls')),
    path('', include('accounts.urls')),
     

]

urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root=settings.MEDIA_ROOT
)

bookshop_app/models.py
from django.db import models
from django.conf import settings 

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    image = models.ImageField(upload_to='book_images/', blank=True, null=True)


    categories = models.ManyToManyField(Category, related_name='books', blank=True)

    def __str__(self):
        return self.title
    
class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def total_price(self):
        return sum(item.subtotal() for item in self.items.all())

    def total_items(self):
        return sum(item.quantity for item in self.items.all())

    def __str__(self):
        return f"Cart of {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name="items", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.book.price * self.quantity

bookshop_app/forms.py
from django import forms

class ContactForm(forms.Form):

    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message= forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'

        self.fields['name'].widget.attrs['class'] = 'form-control'


        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'

        self.fields['email'].widget.attrs['class'] = 'form-control'


        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'

        self.fields['title'].widget.attrs['class'] = 'form-control'


        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力して下さい'

        self.fields['message'].widget.attrs['class'] = 'form-control'

bookshop_app/views.py
from django.shortcuts import render  
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from .models import Cart,CartItem
from .models import Book
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,TemplateView

from django.views.generic import FormView

from django.urls import reverse_lazy

from .forms import ContactForm  

from django.contrib import messages

from django.core.mail import EmailMessage

class IndexView(ListView):
    model = Book
    template_name = 'index.html'
    context_object_name = 'books'
    paginate_by = 6
    


class BookDetailView(DetailView):
    template_name = 'detail.html'
    model = Book
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            cart, _ = Cart.objects.get_or_create(user=self.request.user)
            context['cart'] = cart
        return context
    
    
class CartView(LoginRequiredMixin, TemplateView):
    template_name = 'cart_detail.html'
    login_url = 'accounts:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart, _ = Cart.objects.get_or_create(user=self.request.user)
        context['cart'] = cart
        context['items'] = CartItem.objects.filter(cart=cart)
        return context


@login_required(login_url='accounts:login')
def add_to_cart(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    cart, _ = Cart.objects.get_or_create(user=request.user)


    item = CartItem.objects.filter(cart=cart, book=book).first()
    if item:
        item.quantity += 1
        item.save()
    else:
        CartItem.objects.create(cart=cart, book=book, quantity=1)

    return redirect('bookshop:cart_detail')  

@login_required(login_url='accounts:login')
def cart_detail(request):
    cart, _ = Cart.objects.get_or_create(user=request.user)
    items = cart.items.all()

    total = sum(item.subtotal() for item in items)
    count = sum(item.quantity for item in items)

    return render(request, 'cart_detail.html', {
        'cart': cart,
        'items': items,
        'total': total,
        'count': count,
    })

@login_required(login_url='accounts:login')
def remove_cart_item(request, item_id):
    item = get_object_or_404(CartItem, pk=item_id, cart__user=request.user)
    item.delete()
    return redirect('bookshop:cart_detail')




class ContactView(FormView):

    template_name='contact.html'

    form_class = ContactForm

    success_url=reverse_lazy('bookshop:contact')

    def form_valid(self, form):

        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']

        subject ='お問い合わせ:{}'.format(title)

        message = \
          '送信者名:{0}\n メールアドレス:{1}\n タイトル:{2}\n メッセージ:{3}' \
          .format(name, email, title, message)

        from_email = 'admin@example.com'

        to_list = ['admin@example.com']

        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )

        message.send()

        messages.success(
            self.request, 'お問い合わせは正常に送信されました。'
        )
        return super().form_valid(form)    

bookshop_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>BOOKSHOP</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static "css/bookshop.css" %}" rel="stylesheet" />
        <style>
            .card-img-top {
                width: 100%;
                height: 250px;     
                object-fit: contain; 
                object-position: center;
                background-color: #f3f4f5ff;
            }
        </style>

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'bookshop:index' %}">📚BOOKSHOP📚</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'bookshop:index' %}">Home</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:mypage' %}">Hello, {{ user.username }}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
                            </li>
                        {% endif %}

                    </ul>
                    <a class="btn btn-outline-dark" href="{% url 'bookshop:cart_detail' %}">
                    <i class="bi bi-cart-fill me-1"></i> Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">
                        {% if user.is_authenticated and user.cart %}
                            {{ user.cart.total_items }}
                        {% else %}
                            0
                        {% endif %}
                    </span>
                    </a>
                    <a class="btn btn-outline-dark ms-2" href="{% url 'bookshop:contact' %}">
                    <i class="bi bi-envelope me-1"></i> Contact
                    </a>

                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-3">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">本と暮らす — Living with Books</h1>
                    <p class="lead fw-normal text-white-50 mb-0">選ぶ楽しさ、読む喜びを、あなたに</p>
                </div>
            </div>
        </header>
       <!-- Section: Books -->
        
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="float-end mb-1">
                    <a href="{% url 'bookshop:index' %}">Back to Home</a>
                </p>
                <p class="m-0 text-center text-white">Copyright &copy; BOOKSHOP 2025</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

bookshop_app/templates/book_list.html
{% load static %}

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

      {% for book in books %}
      <div class="col">
        <div class="card shadow-sm">

          {% if book.image %}
          <img src="{{ book.image.url }}"
               class="bd-placeholder-img card-img-top"
               style="height:180px; object-fit:contain; object-position:center;">
          {% endif %}

          <div class="card-body text-center">
            <p class="card-text fw-bold">{{ book.title }}</p>
            <p class="card-text fw-bold">Price: ¥{{ book.price }}</p>

            <div class="d-flex justify-content-center gap-2 mt-2">
              <a href="{% url 'bookshop:book_detail' book.pk %}" class="btn btn-sm btn-outline-secondary">View</a>

              {% if user.is_authenticated %}
                <a href="{% url 'bookshop:add_to_cart' book.pk  %}" class="btn btn-sm btn-dark">🛒 Add to Cart</a>
              {% else %}
                <button class="btn btn-sm btn-secondary" disabled>🛒 Add to Cart</button>
              {% endif %}
            </div>

          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <h5 class="text-center text-danger my-2">
            カートに購入したい場合は Sign up または Login してください！
    </h5>
  </div>
</div>

bookshop_app/templates/cart_detail.html
{% extends "base.html" %}

{% block title %}Your Cart{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="fw-bolder mb-4 text-dark">🛒 Your Cart</h2>

    <div class="card shadow-sm rounded-4">
        <div class="card-body p-4">

            <table class="table align-middle">
                <thead>
                    <tr>
                        <th>Book</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Qty</th>
                        <th class="text-center">Subtotal</th>

                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td class="fw-semibold">{{ item.book.title }}</td>
                        <td class="text-center">¥{{ item.book.price }}</td>
                        <td class="text-center">{{ item.quantity }}</td>
                        <td class="text-center">¥{{ item.subtotal }}</td>
                        <td class="text-center">
                            <a href="{% url 'bookshop:remove_cart_item' item.id %}" class="btn btn-sm btn-danger">
                                🗑 削除
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr><td colspan="4" class="text-center text-muted">カートは空です</td></tr>
                    {% endfor %}
                </tbody>
            </table>

            <hr>

            <div class="text-end">
                <h5 class="text-muted">Total Items: {{ cart }}</h5>
                <h3 class="fw-bold text-dark">Total Price: ¥{{ total }}</h3>
            </div>

        </div>
    </div>
</div>
{% endblock %}

bookshop_app/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<div class="container my-5">

  <h2 class="fw-bold text-center mb-4">📩 Contact Us</h2>

  {% if request.GET.sent %}
  <div class="alert alert-success text-center">
      ✅ お問い合わせ内容を受け取りました！
  </div>
  {% endif %}

  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm rounded-4">
        <div class="card-body p-4">

          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }} text-center">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            <div class="text-center">
              <button type="submit" class="btn btn-dark">Send</button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

bookshop_app/templates/detail.html
{% extends 'base.html' %}
{% block title %}Book Detail{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">  
        <div class="col-md-6 text-center">  
            <h2>{{ object.title }}</h2>
            <p>{{ object.description }}</p>

            {% if object.image %}
            <img src="{{ object.image.url }}"
             alt="{{ object.title }}"
             style="display:block; margin:0 auto; width:auto;
                 max-width:300px; height:200px; object-fit:cover; object-position:center;">
            <br></br>
            {% endif %}
            <p class="card-text  fw-bold">Price: ¥{{ object.price }}</p>
            <p class="mt-3">Categories:
            {% for category in object.categories.all %}
               {{ category.name }}{% if not forloop.last %}, {% endif %}
            {% empty %}
               None
            {% endfor %}
            </p>
            <div class="d-flex justify-content-center gap-2 mt-3">
                {% if user.is_authenticated %}
                    <a href="{% url 'bookshop:add_to_cart' book.pk %}" class="btn btn-sm btn-dark">🛒 Add to Cart</a>
                {% else %}
                    <button class="btn btn-sm btn-secondary" disabled>🛒 Add to Cart </button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookshop_app/templates/index.html
{% extends 'base.html' %}

    {% block content %}

    {% include "book_list.html" %}

    {% include "pagination.html" %}

    {% endblock %}

bookshop_app/templates/pagination.html
<ul class="pagination"
    style="justify-content:center">

    {% if page_obj.has_previous %}


    <li class="page-item">
        <a class="page-link"
        　　 href="?page={{ page_obj.previous_page_number }}"
        　　 aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}

        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>

        {% else %}


        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}

    <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>